// Assembles index.html from the scene list + measured voice-over durations.
// Re-run after changing a scene's narration/audio:  node script/build-index.mjs
// Scene visuals live in compositions/sNN.html and are NOT touched by this script.
import { readFileSync, writeFileSync } from "node:fs";

const here = new URL(".", import.meta.url);
const scenes = JSON.parse(readFileSync(new URL("scenes.json", here)));
const timing = JSON.parse(readFileSync(new URL("timing.json", here)));

const chapters = [
  { id: "ch0", label: "Study Guide", from: "s01", to: "s01" },
  { id: "ch8", label: "§8 · Business Entities", from: "s02", to: "s14" },
  { id: "ch9", label: "§9 · Governance, Ownership & Control", from: "s15", to: "s22" },
  { id: "ch10", label: "§10 · Leverage, Supply Chain & Bias", from: "s23", to: "s26" },
  { id: "ch11", label: "Recap", from: "s27", to: "s27" },
];

const r = (n) => Math.round(n * 1000) / 1000;
let t = 0;
const slots = scenes.map((s) => {
  const tm = timing[s.id];
  const dur = r(tm.lead + tm.audio + tm.tail);
  const slot = { ...s, start: r(t), dur, voStart: r(t + tm.lead), audio: tm.audio };
  t += dur;
  return slot;
});
const total = r(t);
const byId = Object.fromEntries(slots.map((s) => [s.id, s]));

const hosts = slots
  .map(
    (s) => `      <!-- ${s.id} · ${s.title} -->
      <div id="${s.id}" data-composition-id="${s.id}" data-composition-src="compositions/${s.id}.html"
        data-start="${s.start}" data-duration="${s.dur}" data-track-index="1" data-width="1920" data-height="1080"></div>`,
  )
  .join("\n");

const audios = slots
  .map(
    (s) =>
      `      <audio id="vo-${s.id}" src="assets/audio/${s.id}.mp3" data-start="${s.voStart}" data-duration="${r(s.audio)}" data-track-index="10" data-volume="1"></audio>`,
  )
  .join("\n");

const chapterEls = chapters
  .map((c) => {
    const a = byId[c.from].start;
    const b = byId[c.to].start + byId[c.to].dur;
    return `      <div id="hud-${c.id}" class="clip hud-chapter" data-start="${r(a)}" data-duration="${r(b - a)}" data-track-index="3"><span class="hud-dot"></span><span class="hud-text">${c.label}</span></div>`;
  })
  .join("\n");

const chapterTweens = chapters
  .map((c) => `      tl.fromTo("#hud-${c.id} .hud-text", { opacity: 0, x: -16 }, { opacity: 1, x: 0, duration: 0.6, ease: "power2.out" }, ${byId[c.from].start + 0.2});`)
  .join("\n");

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>Business Entities, Governance & Leverage — Study Guide</title>
    <!-- GENERATED by script/build-index.mjs — edit scenes in compositions/, timing in script/timing.json -->
    <script src="assets/vendor/gsap.min.js"></script>
    <link rel="stylesheet" href="assets/theme.css" />
    <style>
      @font-face { font-family: "JetBrains Mono"; src: url("assets/fonts/jetbrains-mono-latin-500-normal.woff2") format("woff2"); font-weight: 500; }
      body { margin: 0; background: #0d1524; }
      #root { position: relative; width: 100%; height: 100%; overflow: hidden; background: #0d1524; }
      #bg { position: absolute; inset: 0; }
      #bg .glow { position: absolute; width: 1400px; height: 1400px; left: 900px; top: -500px; border-radius: 50%;
        background: radial-gradient(circle, rgba(124, 178, 255, 0.10) 0%, rgba(124, 178, 255, 0) 65%); }
      #bg .glow2 { position: absolute; width: 1200px; height: 1200px; left: -500px; top: 400px; border-radius: 50%;
        background: radial-gradient(circle, rgba(245, 176, 65, 0.07) 0%, rgba(245, 176, 65, 0) 65%); }
      #bg .grid { position: absolute; inset: 0; opacity: 0.5;
        background-image: linear-gradient(rgba(244,239,230,0.035) 1px, transparent 1px), linear-gradient(90deg, rgba(244,239,230,0.035) 1px, transparent 1px);
        background-size: 80px 80px; }
      .hud-chapter { position: absolute; left: 150px; top: 64px; display: flex; align-items: center; gap: 16px;
        font-family: "JetBrains Mono", monospace; font-size: 20px; letter-spacing: 0.16em; text-transform: uppercase; color: #a3aec2; }
      .hud-dot { width: 10px; height: 10px; border-radius: 50%; background: #f5b041; }
      #hud-brand { position: absolute; right: 150px; top: 64px; font-family: "JetBrains Mono", monospace; font-size: 20px;
        letter-spacing: 0.16em; text-transform: uppercase; color: #6d7a91; }
      #progress { position: absolute; left: 150px; right: 150px; bottom: 60px; height: 4px; border-radius: 2px; background: rgba(244,239,230,0.1); overflow: hidden; }
      #progress-fill { width: 100%; height: 100%; background: #f5b041; transform-origin: 0 50%; }
    </style>
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-width="1920" data-height="1080" data-duration="${total}">
      <div id="bg"><div class="glow"></div><div class="glow2"></div><div class="grid"></div></div>

      <!-- HUD -->
${chapterEls}
      <div id="hud-brand">Entrepreneurship Fundamentals</div>
      <div id="progress"><div id="progress-fill"></div></div>

      <!-- Scenes -->
${hosts}

      <!-- Voice-over (Higgsfield Seed Speech) -->
${audios}
    </div>
    <script>
      const tl = gsap.timeline({ paused: true });
      tl.fromTo("#progress-fill", { scaleX: 0 }, { scaleX: 1, duration: ${total}, ease: "none" }, 0);
      tl.fromTo("#bg .glow", { x: 0, y: 0 }, { x: -260, y: 120, duration: ${total}, ease: "sine.inOut" }, 0);
      tl.fromTo("#bg .glow2", { x: 0, y: 0 }, { x: 300, y: -160, duration: ${total}, ease: "sine.inOut" }, 0);
${chapterTweens}
      window.__timelines["main"] = tl;
    </script>
  </body>
</html>
`;

writeFileSync(new URL("../index.html", here), html);
writeFileSync(
  new URL("../script/scene-times.json", here),
  JSON.stringify(Object.fromEntries(slots.map((s) => [s.id, { start: s.start, dur: s.dur, vo: s.voStart }])), null, 1),
);
console.log(`index.html: ${slots.length} scenes, ${total}s (${Math.floor(total / 60)}m${Math.round(total % 60)}s)`);
